name: check diff

on:
  push:
    branches:
      - 'main'
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'

jobs:
  check_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v7
        with:
          go-version: stable

      - name: Generate
        run: |
          make generate

      - name: Check diff
        run: |
          git diff --exit-code
