name: spell checking
on: [pull_request]

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: typos-action
      uses: crate-ci/typos@v1.49.0

