name: test

on:
  push:
    branches:
      - 'main'
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
  schedule:
    - cron: '0 8 * * 1' # run "At 08:00 on Monday"ma

jobs:
  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: ['macos-latest', 'windows-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: make test
