name: test

on:
  push:
    branches:
      - 'main'
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
  schedule:
    - cron: '0 8 * * 1' # run "At 08:00 on Monday"ma

jobs:
  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: ['macos-latest', 'windows-latest', 'ubuntu-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go stable
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Test
        run: |
          make test
